### ISSUE TITLE
Some audio meta-information is lost

### ISSUE THREAD

**Issue by JustAMan** [slhck/ffmpeg-normalize#86]
`ffmpeg-normalize` seems to be losing audio track meta information (like language or title).

- [x] ffmpeg-normalize version: v1.3.5 (obtained by `pip3 install` a day ago)
- [x] OS: Debian 9 x86_64
- [x] Python version: stock debian (`python3.5-minimal` deb package, `python -V` says `Python 3.5.3`)
- [x] FFmpeg version: statically linked 4.0.2 64-bit
- [x] The exact command you were trying to run: `/usr/local/bin/ffmpeg-normalize  s01e01.mkv -c:a aac -b:a 400k -pr -t -14 -f`
- [x] Any output you get when running the command with the `--debug` flag: should be irrelevant, encoding finishes just fine.

The problem essentially is that original file has some attributes present on audio tracks which are missing in the normalized one. I'm checking the attributes via `mediainfo` tool.
At least in my case it's missing  `Title` and `Language`, and `Default` and `Forced` values change between original and normalized.

**Comment by michaelcrossland** [comment]
This not something that this script does. It's a know thing that ffmpeg
does to both audio and video tracks. There some help in the documentation
for ffmpeg to not do that but it's something that can't be done very easily
inside of the script. As the placement of the flags needed to make it work
right is different from OS and versions / forks of ffmpeg or whatever the
forks name maybe.

**Comment by michaelcrossland** [comment]
Best thing I can say to get those flags back if for some reason you "just"
got have them in file to make work with whatever software player you're
using. Would be to take the output and rerun it through something like
handbrake for video or use some kind of audio encoder software that will
set those flags. Or if you using an mkv file use the free mkv toolbox app
that let's you go into the file and change things like audio language tags
or video tags like force without having to re-encode your files.

**Comment by slhck** [comment]
Michael, the flags necessary for copying or manipulating metadata are the same across all OSes. Also, while there is at least one big FFmpeg fork (Libav), this script does not support it.

I could reproduce the issue and I have an idea how to solve it.

**Comment by JustAMan** [comment]
Just in case, here's the sample piece that exibits the behaviour: https://filebin.ca/4KeYLmYQqMeT/10sec.mkv (I've put it on the first googled result of "pastebin binary").

The steps:
1. Run `ffmpeg-normalize 10sec.mkv -c:a aac -b:a 400k -pr -t -14 -f -ar 48000`
2. Examine `mediainfo 10sec.mkv` and `mediainfo normalized/10sec.mkv`
3. Note that audio title and language data are gone

**Comment by slhck** [comment]
Thanks, I'll investigate.

**Comment by slhck** [comment]
Fixed in v1.3.7, please update and test!

**Comment by JustAMan** [comment]
Yes, it works now. Thanks!

BTW, your guide on ffmpeg and CRF was awesome :+1:
